'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import AllosLogo from '@/components/AllosLogo';
import { createClient } from '@/lib/supabase/client';

interface Entry {
  id: string;
  title: string;
  content: string;
  mood?: string;
  struggle?: string;
  life_challenge?: string;
  spiritual_need?: string;
  output_type?: string;
  tone?: string;
  notes?: string;
  is_favourite?: boolean;
  created_at: string;
}

function renderOutput(text: string) {
  if (!text) return null;
  const clean = text
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/\*(.+?)\*/g, '$1')
    .replace(/^#{1,6}\s+/gm, '')
    .replace(/^[-]\s+/gm, '')
    .replace(/```[\s\S]*?```/g, '')
    .replace(/`(.+?)`/g, '$1');
  const paragraphs = clean.split(/\n\n+/).filter(p => p.trim());
  return (
    <div style={{ fontFamily: "'Spectral', Georgia, serif", fontSize: '1.05rem', lineHeight: 1.95, color: '#1B3A57' }}>
      {paragraphs.map((para, i) => {
        const lines = para.split('\n').filter(l => l.trim());
        if ((para.includes('"') || para.includes('\u201c')) && /[A-Z][a-z]+ \d+:\d+/.test(para)) {
          return (
            <blockquote key={i} style={{ margin: '1.2em 0', paddingLeft: 20, borderLeft: '3px solid #C8943F', fontStyle: 'italic', color: '#2C5573', fontSize: '1.0rem' }}>
              {lines.map((l, j) => <div key={j}>{l}</div>)}
            </blockquote>
          );
        }
        return <p key={i} style={{ margin: '0 0 1.3em', color: '#1B3A57' }}>{para}</p>;
      })}
    </div>
  );
}

function formatDate(dateStr: string) {
  return new Date(dateStr).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
}

export default function EntryPage({ params }: { params: { id: string } }) {
  const [entry, setEntry] = useState<Entry | null>(null);
  const [notes, setNotes] = useState('');
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [loading, setLoading] = useState(true);
  const [userName, setUserName] = useState('');
  const router = useRouter();
  const supabase = createClient();

  useEffect(() => {
    async function init() {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) { router.push('/auth/login'); return; }
      const { data: profile } = await supabase
        .from('profiles')
        .select('first_name')
        .eq('id', user.id)
        .single();
      const name = profile?.first_name ||
        user.user_metadata?.full_name?.split(' ')[0] ||
        user.user_metadata?.name?.split(' ')[0] || '';
      setUserName(name);

      const res = await fetch('/api/journey/' + params.id);
      if (res.ok) {
        const d = await res.json();
        setEntry(d.entry);
        setNotes(d.entry?.notes || '');
      }
      setLoading(false);
    }
    init();
  }, [params.id]);

  async function saveNotes() {
    if (!entry) return;
    setSaving(true); setSaved(false);
    await fetch('/api/journey/' + entry.id, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ notes }),
    });
    setSaving(false); setSaved(true);
    setTimeout(() => setSaved(false), 2500);
  }

  async function toggleFavourite() {
    if (!entry) return;
    const newVal = !entry.is_favourite;
    setEntry({ ...entry, is_favourite: newVal });
    await fetch('/api/journey/' + entry.id, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ is_favourite: newVal }),
    });
  }

  async function handleSignOut() {
    await supabase.auth.signOut();
    router.push('/');
  }

  // Share helpers
  function shareWhatsApp() {
    if (!entry) return;
    const text = entry.title + '\n\n' + entry.content.substring(0, 300) + '...\n\nGenerated by Allos — word2go.com';
    window.open('https://wa.me/?text=' + encodeURIComponent(text), '_blank');
  }
  function shareX() {
    if (!entry) return;
    const text = entry.title.substring(0, 100) + ' — via @Allos_app word2go.com';
    window.open('https://twitter.com/intent/tweet?text=' + encodeURIComponent(text), '_blank');
  }
  function copyText() {
    if (!entry) return;
    navigator.clipboard.writeText(entry.content).catch(() => {});
  }
  function shareEmail() {
    if (!entry) return;
    window.location.href = 'mailto:?subject=' + encodeURIComponent('Scripture for this season — ' + entry.title) + '&body=' + encodeURIComponent(entry.content + '\n\n— Shared from Allos (word2go.com)');
  }

  return (
    <main style={{ minHeight: '100vh', background: '#F6F9FB', fontFamily: 'Hanken Grotesk, sans-serif' }}>
      {/* Nav */}
      <header style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '14px 24px', borderBottom: '1px solid #DBE5EE', background: '#F6F9FB' }}>
        <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: 10, textDecoration: 'none' }}>
          <AllosLogo size={32} variant="light" />
          <span style={{ fontFamily: "'Spectral', Georgia, serif", fontWeight: 500, fontSize: '1.1rem', color: '#1B3A57', letterSpacing: '-0.01em' }}>Allos</span>
        </Link>
        <div style={{ display: 'flex', gap: 16, alignItems: 'center' }}>
          {userName && <span style={{ fontSize: '0.85rem', color: '#54677A' }}>Welcome back, {userName}</span>}
          <Link href="/journey" style={{ fontSize: '0.85rem', color: '#6E9CC4', textDecoration: 'none', fontWeight: 500 }}>← Journey</Link>
          <button onClick={handleSignOut} style={{ fontSize: '0.8rem', color: '#54677A', background: 'none', border: 'none', cursor: 'pointer', fontFamily: 'Hanken Grotesk, sans-serif' }}>Sign out</button>
        </div>
      </header>

      <div style={{ maxWidth: 640, margin: '0 auto', padding: '40px 24px 80px' }}>
        {loading && (
          <div style={{ textAlign: 'center', padding: '60px 0', color: '#54677A', fontSize: '0.9rem' }}>Loading entry...</div>
        )}

        {!loading && !entry && (
          <div style={{ textAlign: 'center', padding: '60px 0' }}>
            <p style={{ color: '#54677A', marginBottom: 16 }}>Entry not found.</p>
            <Link href="/journey" style={{ color: '#6E9CC4', textDecoration: 'none', fontWeight: 500 }}>← Back to Journey</Link>
          </div>
        )}

        {!loading && entry && (
          <>
            {/* Header */}
            <div style={{ marginBottom: 28 }}>
              <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 10 }}>
                {entry.mood && <span style={{ fontSize: '0.7rem', fontWeight: 700, letterSpacing: '0.28em', textTransform: 'uppercase', color: '#6E9CC4' }}>{entry.mood}</span>}
                {entry.output_type && <span style={{ fontSize: '0.7rem', color: '#54677A' }}>· {entry.output_type}</span>}
                {entry.tone && <span style={{ fontSize: '0.7rem', color: '#54677A' }}>· {entry.tone}</span>}
              </div>
              <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 }}>
                <h1 style={{ fontFamily: "'Spectral', Georgia, serif", fontWeight: 300, fontSize: 'clamp(22px,3.5vw,32px)', color: '#1B3A57', margin: 0, lineHeight: 1.25, flex: 1 }}>{entry.title}</h1>
                <button
                  onClick={toggleFavourite}
                  title={entry.is_favourite ? 'Remove from favourites' : 'Add to favourites'}
                  style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: 24, color: entry.is_favourite ? '#C8943F' : '#DBE5EE', flexShrink: 0 }}
                >
                  {entry.is_favourite ? '★' : '☆'}
                </button>
              </div>
              <p style={{ color: '#54677A', fontSize: '0.82rem', marginTop: 8 }}>{formatDate(entry.created_at)}</p>
            </div>

            {/* Content card */}
            <div style={{ background: '#fff', borderRadius: 20, border: '1px solid #DBE5EE', padding: '28px 28px 24px', marginBottom: 20 }}>
              {renderOutput(entry.content)}
            </div>

            {/* Share buttons */}
            <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', marginBottom: 28 }}>
              <button onClick={copyText} style={{ background: '#E8F0F7', border: 'none', borderRadius: 100, padding: '9px 18px', fontSize: '0.82rem', fontWeight: 600, color: '#1B3A57', cursor: 'pointer', fontFamily: 'Hanken Grotesk, sans-serif' }}>Copy text</button>
              <button onClick={shareWhatsApp} style={{ background: '#E8F0F7', border: 'none', borderRadius: 100, padding: '9px 18px', fontSize: '0.82rem', fontWeight: 600, color: '#1B3A57', cursor: 'pointer', fontFamily: 'Hanken Grotesk, sans-serif' }}>WhatsApp</button>
              <button onClick={shareX} style={{ background: '#E8F0F7', border: 'none', borderRadius: 100, padding: '9px 18px', fontSize: '0.82rem', fontWeight: 600, color: '#1B3A57', cursor: 'pointer', fontFamily: 'Hanken Grotesk, sans-serif' }}>Post on X</button>
              <button onClick={shareEmail} style={{ background: '#E8F0F7', border: 'none', borderRadius: 100, padding: '9px 18px', fontSize: '0.82rem', fontWeight: 600, color: '#1B3A57', cursor: 'pointer', fontFamily: 'Hanken Grotesk, sans-serif' }}>Email</button>
            </div>

            {/* Notes */}
            <div style={{ background: '#fff', borderRadius: 20, border: '1px solid #DBE5EE', padding: '24px 28px' }}>
              <div style={{ fontSize: '0.7rem', fontWeight: 700, letterSpacing: '0.28em', textTransform: 'uppercase', color: '#6E9CC4', marginBottom: 12 }}>Reflection notes</div>
              <textarea
                value={notes}
                onChange={e => setNotes(e.target.value)}
                placeholder="Write your reflections here..."
                rows={5}
                style={{ width: '100%', border: '1px solid #DBE5EE', borderRadius: 10, padding: '12px 14px', fontFamily: "'Spectral', Georgia, serif", fontSize: '0.95rem', lineHeight: 1.7, color: '#1B3A57', background: '#F6F9FB', resize: 'vertical', outline: 'none', boxSizing: 'border-box' }}
              />
              <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginTop: 12 }}>
                <button
                  onClick={saveNotes}
                  disabled={saving}
                  style={{ background: '#1B3A57', color: '#F6F9FB', border: 'none', borderRadius: 100, padding: '10px 24px', fontSize: '0.88rem', fontWeight: 600, cursor: saving ? 'not-allowed' : 'pointer', opacity: saving ? 0.7 : 1, fontFamily: 'Hanken Grotesk, sans-serif' }}
                >
                  {saving ? 'Saving...' : 'Save notes'}
                </button>
                {saved && <span style={{ fontSize: '0.82rem', color: '#C8943F', fontFamily: "'Spectral', Georgia, serif", fontStyle: 'italic' }}>Saved ✓</span>}
              </div>
            </div>
          </>
        )}
      </div>
    </main>
  );
}