'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import AllosLogo from '@/components/AllosLogo';
import { createClient } from '@/lib/supabase/client';

interface Entry {
  id: string; title: string; content: string;
  mood?: string; struggle?: string; life_challenge?: string; spiritual_need?: string;
  output_type?: string; tone?: string; notes?: string; is_favourite?: boolean; created_at: string;
}

function renderOutput(text: string) {
  if (!text) return null;
  const clean = text
    .replace(/\*\*(.+?)\*\*/g, '$1').replace(/\*(.+?)\*/g, '$1')
    .replace(/^#{1,6}\s+/gm, '').replace(/^[-]\s+/gm, '')
    .replace(/```[\s\S]*?```/g, '').replace(/`(.+?)`/g, '$1');
  const paragraphs = clean.split(/\n\n+/).filter(p => p.trim());
  return (
    <div style={{ fontFamily: "'Spectral', Georgia, serif", fontSize: '1.05rem', lineHeight: 1.95, color: '#0F2B45' }}>
      {paragraphs.map((para, i) => {
        const lines = para.split('\n').filter(l => l.trim());
        if ((para.includes('"') || para.includes('\u201c')) && /[A-Z][a-z]+ \d+:\d+/.test(para)) {
          return (
            <blockquote key={i} style={{ margin: '1.2em 0', paddingLeft: 20, borderLeft: '3px solid #B8832A', fontStyle: 'italic', color: '#1A3F5C', fontSize: '1.0rem' }}>
              {lines.map((l, j) => <div key={j}>{l}</div>)}
            </blockquote>
          );
        }
        return <p key={i} style={{ margin: '0 0 1.3em', color: '#0F2B45' }}>{para}</p>;
      })}
    </div>
  );
}

function formatDate(dateStr: string) {
  return new Date(dateStr).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
}

export default function EntryPage({ params }: { params: { id: string } }) {
  const [entry, setEntry] = useState<Entry | null>(null);
  const [notes, setNotes] = useState('');
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [loading, setLoading] = useState(true);
  const [userName, setUserName] = useState('');
  const router = useRouter();
  const supabase = createClient();

  useEffect(() => {
    async function init() {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) { router.push('/auth/login'); return; }
      const { data: profile } = await supabase.from('profiles').select('first_name').eq('id', user.id).single();
      setUserName(profile?.first_name || user.user_metadata?.full_name?.split(' ')[0] || user.user_metadata?.name?.split(' ')[0] || '');
      const res = await fetch('/api/journey/' + params.id);
      if (res.ok) { const d = await res.json(); setEntry(d.entry); setNotes(d.entry?.notes || ''); }
      setLoading(false);
    }
    init();
  }, [params.id]);

  async function saveNotes() {
    if (!entry) return;
    setSaving(true); setSaved(false);
    await fetch('/api/journey/' + entry.id, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ notes }) });
    setSaving(false); setSaved(true);
    setTimeout(() => setSaved(false), 2500);
  }

  async function toggleFavourite() {
    if (!entry) return;
    const newVal = !entry.is_favourite;
    setEntry({ ...entry, is_favourite: newVal });
    await fetch('/api/journey/' + entry.id, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ is_favourite: newVal }) });
  }

  function shareWhatsApp() { if (!entry) return; window.open('https://wa.me/?text=' + encodeURIComponent(entry.title + '\n\n' + entry.content.substring(0, 300) + '...\n\nGenerated by Allos \u2014 word2go.com'), '_blank'); }
  function shareX() { if (!entry) return; window.open('https://twitter.com/intent/tweet?text=' + encodeURIComponent(entry.title.substring(0, 100) + ' \u2014 via @Allos_app word2go.com'), '_blank'); }
  function copyText() { if (!entry) return; navigator.clipboard.writeText(entry.content).catch(() => {}); }
  function shareEmail() { if (!entry) return; window.location.href = 'mailto:?subject=' + encodeURIComponent('Scripture for this season \u2014 ' + entry.title) + '&body=' + encodeURIComponent(entry.content + '\n\n\u2014 Shared from Allos (word2go.com)'); }

  return (
    <main style={{ minHeight: '100vh', background: '#FFFFFF', fontFamily: 'Hanken Grotesk, sans-serif' }}>
      <header style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '14px 24px', borderBottom: '1px solid #C8D8E8', background: '#FFFFFF' }}>
        <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: 10, textDecoration: 'none' }}>
          <AllosLogo size={32} variant="light" />
          <span style={{ fontFamily: "'Spectral', Georgia, serif", fontWeight: 500, fontSize: '1.1rem', color: '#0F2B45', letterSpacing: '-0.01em' }}>Allos</span>
        </Link>
        <div style={{ display: 'flex', gap: 16, alignItems: 'center' }}>
          {userName && <span style={{ fontSize: '0.85rem', color: '#3D5166' }}>Welcome back, {userName}</span>}
          <Link href="/journey" style={{ fontSize: '0.85rem', color: '#4A7299', textDecoration: 'none', fontWeight: 500 }}>\u2190 Journey</Link>
          <button onClick={async () => { await supabase.auth.signOut(); router.push('/'); }} style={{ fontSize: '0.8rem', color: '#3D5166', background: 'none', border: 'none', cursor: 'pointer', fontFamily: 'Hanken Grotesk, sans-serif' }}>Sign out</button>
        </div>
      </header>

      <div style={{ maxWidth: 640, margin: '0 auto', padding: '40px 24px 80px' }}>
        {loading && <div style={{ textAlign: 'center', padding: '60px 0', color: '#3D5166', fontSize: '0.9rem' }}>Loading entry...</div>}

        {!loading && !entry && (
          <div style={{ textAlign: 'center', padding: '60px 0' }}>
            <p style={{ color: '#3D5166', marginBottom: 16 }}>Entry not found.</p>
            <Link href="/journey" style={{ color: '#4A7299', textDecoration: 'none', fontWeight: 500 }}>\u2190 Back to Journey</Link>
          </div>
        )}

        {!loading && entry && (
          <>
            <div style={{ marginBottom: 28 }}>
              <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 10 }}>
                {entry.mood && <span style={{ fontSize: '0.7rem', fontWeight: 700, letterSpacing: '0.28em', textTransform: 'uppercase', color: '#4A7299' }}>{entry.mood}</span>}
                {entry.output_type && <span style={{ fontSize: '0.7rem', color: '#3D5166' }}>\u00b7 {entry.output_type}</span>}
                {entry.tone && <span style={{ fontSize: '0.7rem', color: '#3D5166' }}>\u00b7 {entry.tone}</span>}
              </div>
              <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 }}>
                <h1 style={{ fontFamily: "'Spectral', Georgia, serif", fontWeight: 300, fontSize: 'clamp(22px,3.5vw,32px)', color: '#0F2B45', margin: 0, lineHeight: 1.25, flex: 1 }}>{entry.title}</h1>
                <button onClick={toggleFavourite} title={entry.is_favourite ? 'Remove from favourites' : 'Add to favourites'} style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: 24, color: entry.is_favourite ? '#B8832A' : '#C8D8E8', flexShrink: 0 }}>
                  {entry.is_favourite ? '\u2605' : '\u2606'}
                </button>
              </div>
              <p style={{ color: '#3D5166', fontSize: '0.82rem', marginTop: 8 }}>{formatDate(entry.created_at)}</p>
            </div>

            <div style={{ background: '#FFFFFF', borderRadius: 20, border: '1px solid #C8D8E8', padding: '28px 28px 24px', marginBottom: 20, boxShadow: '0 2px 12px rgba(15,43,69,0.06)' }}>
              {renderOutput(entry.content)}
            </div>

            <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', marginBottom: 28 }}>
              <button onClick={copyText} style={{ background: '#F0F5FA', border: 'none', borderRadius: 100, padding: '9px 18px', fontSize: '0.82rem', fontWeight: 600, color: '#0F2B45', cursor: 'pointer', fontFamily: 'Hanken Grotesk, sans-serif' }}>Copy text</button>
              <button onClick={shareWhatsApp} style={{ background: '#F0F5FA', border: 'none', borderRadius: 100, padding: '9px 18px', fontSize: '0.82rem', fontWeight: 600, color: '#0F2B45', cursor: 'pointer', fontFamily: 'Hanken Grotesk, sans-serif' }}>WhatsApp</button>
              <button onClick={shareX} style={{ background: '#F0F5FA', border: 'none', borderRadius: 100, padding: '9px 18px', fontSize: '0.82rem', fontWeight: 600, color: '#0F2B45', cursor: 'pointer', fontFamily: 'Hanken Grotesk, sans-serif' }}>Post on X</button>
              <button onClick={shareEmail} style={{ background: '#F0F5FA', border: 'none', borderRadius: 100, padding: '9px 18px', fontSize: '0.82rem', fontWeight: 600, color: '#0F2B45', cursor: 'pointer', fontFamily: 'Hanken Grotesk, sans-serif' }}>Email</button>
            </div>

            <div style={{ background: '#FFFFFF', borderRadius: 20, border: '1px solid #C8D8E8', padding: '24px 28px' }}>
              <div style={{ fontSize: '0.7rem', fontWeight: 700, letterSpacing: '0.28em', textTransform: 'uppercase', color: '#4A7299', marginBottom: 12 }}>Reflection notes</div>
              <textarea value={notes} onChange={e => setNotes(e.target.value)} placeholder="Write your reflections here..." rows={5}
                style={{ width: '100%', border: '1px solid #C8D8E8', borderRadius: 10, padding: '12px 14px', fontFamily: "'Spectral', Georgia, serif", fontSize: '0.95rem', lineHeight: 1.7, color: '#0F2B45', background: '#FFFFFF', resize: 'vertical', outline: 'none', boxSizing: 'border-box' }}
              />
              <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginTop: 12 }}>
                <button onClick={saveNotes} disabled={saving}
                  style={{ background: '#0F2B45', color: '#FFFFFF', border: 'none', borderRadius: 100, padding: '10px 24px', fontSize: '0.88rem', fontWeight: 600, cursor: saving ? 'not-allowed' : 'pointer', opacity: saving ? 0.7 : 1, fontFamily: 'Hanken Grotesk, sans-serif' }}>
                  {saving ? 'Saving...' : 'Save notes'}
                </button>
                {saved && <span style={{ fontSize: '0.82rem', color: '#B8832A', fontFamily: "'Spectral', Georgia, serif", fontStyle: 'italic' }}>Saved \u2713</span>}
              </div>
            </div>
          </>
        )}
      </div>
    </main>
  );
}
